version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - RUST_LOG=info
      - PORT=8000
